### ISSUE TITLE
fuckin tree not working, as downloaded master.zip and index.html

### ISSUE THREAD

**Issue by ducho** [ExactTarget/fuelux#1033]
fuckin tree not working, as downloaded master.zip and index.html

			<ul class="tree tree-folder-select" role="tree" id="MyTree">
			  <li class="tree-branch hide" data-template="treebranch" role="treeitem" aria-expanded="false">
			    <div class="tree-branch-header">
			      <button class="glyphicon icon-caret glyphicon-play"><span class="sr-only">Open</span></button>
			      <button class="tree-branch-name">
			        <span class="glyphicon icon-folder glyphicon-folder-close"></span>
			        <span class="tree-label"></span>
			      </button>
			    </div>
			    <ul class="tree-branch-children" role="group"></ul>
			    <div class="tree-loader" role="alert">Loading...</div>
			  </li>
			  <li class="tree-item hide" data-template="treeitem" role="treeitem">
			    <button class="tree-item-name">
			      <span class="glyphicon icon-item fueluxicon-bullet"></span>
			      <span class="tree-label"></span>
			    </button>
			  </li>
			</ul>

	$('#myTree').tree({
		dataSource: function(options, callback){
			console.log(options.type);
			setTimeout(function () {
				callback({ data: [
					{ text: 'Ascending and Descending', type: 'folder', dataAttributes: { id: 'F1' } },
					{ text: 'Drawing Hands', type: 'folder', dataAttributes: { id: 'F2' } },
					{ text: 'Belvedere', type: 'folder', dataAttributes: { id: 'F3' } },
					{ text: 'House of Stairs', type: 'folder', dataAttributes: { id: 'F4' } },
					{ text: 'Belvedere', type: 'folder', dataAttributes: { id: 'F5' } }
				]});
			}, 400);},
		cacheItems: false,
		folderSelect: true,
		multiSelect: false
	});

	$('#myTree').on('selected.fu.tree', function (e, info) {
		console.log('Select Event: ', info);
	});

**Comment by ducho** [comment]
strictly speaking ... not working in bootstrap modal window... any tips?

**Comment by mbeard** [comment]
At quick glance, I noticed your selectors are different case.  The id attribute in the markup is `MyTree` but the jquery selectors are `#myTree`

**Comment by ducho** [comment]
Thanks, this I already fixed... but problem is in modal dialog with form .... now I change open modal event but... after clicking on tree item this still submit form... :( sorry for my pure english

**Comment by swilliamset** [comment]
Could you reproduce in a codepen (or other [preferred sandbox](http://www.sitepoint.com/7-code-playgrounds/)) so we can take a closer look?

**Comment by ducho** [comment]
@swilliamset sorry but it would take very long time... to prepare in codepen...
but still not working in version 3.5.1 - 3.0.2 ... with error: 

this.options.dataSource is not a function (fuelux.js:2844)

json result on url /ftp/get_directory_tree: 
{"status":"OK","data":{"name":"South Africa","type":"folder","additionalParameters":{"id":"1"}}}

var DataSourceTree = function (options) {
        this.url = options.url;
}

	DataSourceTree.prototype.data = function (options, callback) {
	    var self = this;
	    var $data = null;
	    var param = null

	    if (!("name" in options) && !("type" in options)) {
	        param = 0; //load the first level
	    } else if ("type" in options && options.type == "folder") {
	        if ("additionalParameters" in options && "children" in options.additionalParameters) {
	            param = options.additionalParameters["id"];
	        }
	    }

	    if (param != null) {
	        $.ajax({
	            url: this.url,
	            data: 'id=' + param,
	            type: 'POST',
	            dataType: 'json',
	            success: function (response) {
	                callback(response)
	            },
	            error: function (response) {
	                console.log(response);
	            }
	        })
	    }
	};



	$('.modal').on('shown.bs.modal', function(e) {

		$("input[type=text]:first").focus();

		$('#myTree').tree({
			dataSource: new DataSourceTree({
	            url: '/ftp/get_directory_tree'
	        }),
			cacheItems: false,
			folderSelect: true,
			multiSelect: false
		});


		$('#myTree').on('selected.fu.tree', function (e, info) {
			console.log('Select Event: ', info);
		});

	})

**Comment by mbeard** [comment]
Here's a codepen [example](http://codepen.io/anon/pen/RNjWGO) with the tree within a modal.  Sounds like your issue now though is the datasource provider.  

Here is a [gist](https://gist.github.com/mbeard/1f4d25e29f3f9de498ce) as well for setting up your own datasource.  Note: it uses underscore to handle paging/sorting/filtering/etc. but since you're making an ajax call, yours would be slightly different.

**Comment by interactivellama** [comment]
I'm sorry that your frustrated. Here is also a tutorial about the tree that may help also. http://fuelux-tutorials.herokuapp.com/tree/

**Comment by mbeard** [comment]
Going to close this issue.  If the above examples don't resolve for you, please reopen and provide a snippet to reproduce.
